# Generated by Django 2.2.16 on 2021-05-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnum', models.IntegerField(verbose_name='SUBNUM')),
                ('subname', models.CharField(max_length=20, verbose_name='SUBNAME')),
                ('subyear', models.DateTimeField(blank=True, null=True, verbose_name='SUBYEAR')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='SEMESTER')),
                ('professor', models.CharField(blank=True, max_length=10, null=True, verbose_name='PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stunum', models.IntegerField(verbose_name='STUNUM')),
                ('stuname', models.CharField(max_length=10, verbose_name='STUNAME')),
                ('password', models.CharField(max_length=30, verbose_name='PASSWORD')),
                ('phonenum', models.CharField(blank=True, max_length=15, null=True, verbose_name='PHONENUM')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='EMAIL')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignnum', models.IntegerField(verbose_name='ASSIGNNUM')),
                ('assigntitle', models.CharField(max_length=100, verbose_name='ASSIGNTITLE')),
                ('assigncontent', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ASSIGNCONTENT')),
                ('duedate', models.DateTimeField(blank=True, null=True, verbose_name='DUEDATE')),
                ('result', models.CharField(blank=True, max_length=20, null=True, verbose_name='RESULT')),
                ('subj_subname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subname_assign', to='schedule.Subject')),
                ('subj_subnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnum_assgin', to='schedule.Subject')),
            ],
        ),
    ]
