# Generated by Django 2.2.16 on 2021-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subday',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='SUBDAY'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subyear',
            field=models.DateField(blank=True, null=True, verbose_name='SUBYEAR'),
        ),
    ]
