# Generated by Django 2.2.16 on 2021-05-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210527_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
