# Generated by Django 2.2.16 on 2021-05-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subj_subnum',
        ),
    ]
