# Generated by Django 2.2.16 on 2021-05-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_assignment_subj_subnum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('duedate',)},
        ),
    ]
