# Generated by Django 2.2.16 on 2021-05-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_assignment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subj_subname',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject'),
        ),
    ]
