# Generated by Django 2.2.16 on 2021-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_assignment_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
