# Generated by Django 2.2.16 on 2021-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subyear',
            field=models.IntegerField(blank=True, null=True, verbose_name='SUBYEAR'),
        ),
    ]
