# Generated by Django 2.2.16 on 2021-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210529_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subyear',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='SUBYEAR'),
        ),
    ]
