# Generated by Django 2.2.16 on 2021-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20210529_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subyear',
            field=models.DateField(blank=True, null=True, verbose_name='SUBYEAR'),
        ),
    ]
