# Generated by Django 2.2.16 on 2021-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20210529_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='YEAR'),
        ),
    ]
