# Generated by Django 2.2.16 on 2021-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_subject_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
    ]
